### ISSUE TITLE
Błąd w pytaniu

### ISSUE THREAD

**Issue by CircuitChaos** [ixeeek/sq5ps-zgloszenia#2]
Prośba, dawajcie całe pytanie, wzięte z strony, również dawajcie cale odpowiedzi - ułatwi mi to poprawe tego pytania w bazie danych jesli sugestia okaze sie sluszna :D

# Przedmiot (np. "procedury"):
Radiotechnika

# Pytanie (calosc pytania np. "Co oznacza wg kodu Q symbol QRG?"):
Zasadniczym przeznaczeniem diody PIN jest:

# Obecna poprawna odpowiedz (ta podawana przez stronę):
Prostowanie bardzo dużych napięć i prądów

# Proponowana wlasciwia odpowiedz (np. "moja częstotliwość jest…"):
Stosowanie jej jako przełącznika w.cz.

# Wyjasnienie (dlaczego ta odpowiedz a nie inna):
Bo (celowo) nie jest dość szybka, żeby się przełączać przy w.cz., więc robi za rezystor zależnie od stałego napięcia polaryzującego.

Ogólnie: dobra robota!

**Comment by ixeeek** [comment]
Poprawione :D
