### ISSUE TITLE
Zaznaczanie odpowiedzi

### ISSUE THREAD

**Issue by CircuitChaos** [ixeeek/sq5ps-zgloszenia#3]
Nie da się zaznaczyć odpowiedzi do skopiowania do formularza zgłoszenia błędu w pytaniu, musiałem przepisywać.

**Comment by ixeeek** [comment]
Da sie, w zwiazku z tym ze odpowiedzi sa buttonami, trzeba zaznaczac po prawej lub lewej (nie na samym guziku)

**Comment by ixeeek** [comment]
<img width="1444" alt="image" src="https://github.com/ixeeek/sq5ps-zgloszenia/assets/67503809/f3de63ec-12b6-415f-9ae0-847c2c7640b0">
tutaj "dowod" ze sie da. Rozumiem ze troche niewygodne ale tak pozostanie - muslabym zupelnie przepisac system guzikow do odpowiedzi

**Comment by CircuitChaos** [comment]
Ok, jasne. To może warto o tym napisać w formularzu zgłoszenia? Chciałem sprawdzić, ale teraz strona się nie ładuje (tzn. sama strona działa, ale kręci się kółko ładowania) – podejrzewam że dlatego, że coś teraz robisz :)

**Comment by ixeeek** [comment]
Juz dziala, szczerze mowiac zapomnialem jednej rzeczy na proda dac

**Comment by CircuitChaos** [comment]
Tak, już tak. Co ciekawe, zaznaczanie tekstu przycisku działa w Chromium, ale nie działa w FF.

**Comment by ixeeek** [comment]
I tak szczerze mowiac na ten moment nie mam jak tego zmienic, tak wiec zamykam. W kazdym razie dziekuje za zgloszenie
