### ISSUE TITLE
Błąd w pytaniu

### ISSUE THREAD

**Issue by CircuitChaos** [ixeeek/sq5ps-zgloszenia#5]
Prośba, dawajcie całe pytanie, wzięte z strony, również dawajcie cale odpowiedzi - ułatwi mi to poprawe tego pytania w bazie danych jesli sugestia okaze sie sluszna :D

# Przedmiot (np. "procedury"):
BHP

# Pytanie (calosc pytania np. "Co oznacza wg kodu Q symbol QRG?"):
Jakim przewodem podłączysz nadajnik dużej mocy do źródła zasilania?

# Obecna poprawna odpowiedz (ta podawana przez stronę):
Przewodem o przekroju żył, odpowiednim do pobieranej przez urządzenie mocy

# Proponowana wlasciwia odpowiedz (np. "moja częstotliwość jest…"):
Przewodem o przekroju żył odpowiednim do pobieranej przez urządzenie mocy

# Wyjasnienie (dlaczego ta odpowiedz a nie inna):
Chodzi o przecinek :)

**Comment by ixeeek** [comment]
Poprawione :D
