### ISSUE TITLE
[BUG] Prefiks kraju znajduje się

### ISSUE THREAD

**Issue by Radiowski** [ixeeek/sq5ps-zgloszenia#6]
Prośba, dawajcie całe pytanie, wzięte z strony, również dawajcie cale odpowiedzi - ułatwi mi to poprawe tego pytania w bazie danych jesli sugestia okaze sie sluszna :D

# Przedmiot (np. "procedury"):
przepisy

# Pytanie (calosc pytania np. "Co oznacza wg kodu Q symbol QRG?"):
Prefiks kraju znajduje się 

# Obecna poprawna odpowiedz (ta podawana przez stronę):
zadna

# Proponowana wlasciwia odpowiedz (np. "moja częstotliwość jest…"):
na początku znaku wywoławczego stacji amatorskiej

# Wyjasnienie (dlaczego ta odpowiedz a nie inna):
Ponieważ na początku znaku stacji amatorskiej znajduje się prefiks kraju.

**Comment by ixeeek** [comment]
Poprawione :D
